create table BridgeTable(Code varchar(10), CName varchar(40));



insert into BridgeTable values('RCA', 'Central African Rep.');
insert into BridgeTable values('COCO', 'Cocos Island');
insert into BridgeTable values('RCB', 'Congo, Dem. Rep.');
insert into BridgeTable values('RCB', 'Congo, Rep.');
insert into BridgeTable values('CI', 'Cote d''Ivoire');
insert into BridgeTable values('CZ', 'Czech Rep.');
insert into BridgeTable values('DOM', 'Dominican Rep.');
insert into BridgeTable values('FALK', 'Falkland Islands (Malvinas)');
insert into BridgeTable values('HONX', 'Hong Kong, China');
insert into BridgeTable values('FARX', 'Faeroe Islands');
insert into BridgeTable values('KAZ', 'Kazakhstan');
insert into BridgeTable values('MACX', 'Macao, China');
insert into BridgeTable values('MK', 'Macedonia, FYR');
insert into BridgeTable values('FSM', 'Micronesia, Fed. Sts.');
insert into BridgeTable values('ROK', 'South Korea');
insert into BridgeTable values('NOK', 'North Korea');
insert into BridgeTable values(NULL, 'Korea, United');
insert into BridgeTable values('PITC', 'Pitcairn');
insert into BridgeTable values('SPMI', 'Saint-Pierre-et-Miquelon');
insert into BridgeTable values('SK', 'Slovak Republic');
insert into BridgeTable values('VIRG', 'Virgin Islands (U.S.)');
insert into BridgeTable values('WAFU', 'Wallis et Futuna');
insert into BridgeTable values('WEST', 'West Bank and Gaza');
insert into BridgeTable values('YE', 'Yemen Arab Republic (Former)');
insert into BridgeTable values('YE', 'Yemen Democratic (Former)');
insert into BridgeTable values('YE', 'Yemen, Rep.');
insert into BridgeTable values('D', 'East Germany');
insert into BridgeTable values('D', 'West Germany');
insert into BridgeTable values('GAZA', NULL);
insert into BridgeTable values('GBM', NULL);
insert into BridgeTable values('ZRE', NULL);
insert into BridgeTable values(NULL, 'Abkhazia');
insert into BridgeTable values(NULL, 'Akrotiri and Dhekelia');
insert into BridgeTable values(NULL, 'Åland');
insert into BridgeTable values(NULL, 'Channel Islands');
insert into BridgeTable values(NULL, 'Czechoslovakia');
insert into BridgeTable values(NULL, 'Eritrea and Ethiopia');
insert into BridgeTable values(NULL, 'Isle of Man');
insert into BridgeTable values(NULL, 'Nagorno-Karabakh');
insert into BridgeTable values(NULL, 'Ngorno-Karabakh');
insert into BridgeTable values(NULL, 'Northern Cyprus');
insert into BridgeTable values(NULL, 'Saint Barthélemy');
insert into BridgeTable values(NULL, 'Serbia and Montenegro');
insert into BridgeTable values(NULL, 'Serbia excluding Kosovo');
insert into BridgeTable values(NULL, 'Somaliland');
insert into BridgeTable values(NULL, 'South Ossetia');
insert into BridgeTable values(NULL, 'Tokelau');
insert into BridgeTable values(NULL, 'Transnistria');
insert into BridgeTable values(NULL, 'USSR');
insert into BridgeTable values(NULL, 'Yugoslavia');


insert into BridgeTable values('AFG', 'Afghanistan');
insert into BridgeTable values('AL', 'Albania');
insert into BridgeTable values('DZ', 'Algeria');
insert into BridgeTable values('AMSA', 'American Samoa');
insert into BridgeTable values('AND', 'Andorra');
insert into BridgeTable values('ANG', 'Angola');
insert into BridgeTable values('AXA', 'Anguilla');
insert into BridgeTable values('AG', 'Antigua and Barbuda');
insert into BridgeTable values('RA', 'Argentina');
insert into BridgeTable values('ARM', 'Armenia');
insert into BridgeTable values('ARU', 'Aruba');
insert into BridgeTable values('AUS', 'Australia');
insert into BridgeTable values('A', 'Austria');
insert into BridgeTable values('AZ', 'Azerbaijan');
insert into BridgeTable values('BS', 'Bahamas');
insert into BridgeTable values('BRN', 'Bahrain');
insert into BridgeTable values('BD', 'Bangladesh');
insert into BridgeTable values('BDS', 'Barbados');
insert into BridgeTable values('BY', 'Belarus');
insert into BridgeTable values('B', 'Belgium');
insert into BridgeTable values('BZ', 'Belize');
insert into BridgeTable values('BEN', 'Benin');
insert into BridgeTable values('BERM', 'Bermuda');
insert into BridgeTable values('BHT', 'Bhutan');
insert into BridgeTable values('BOL', 'Bolivia');
insert into BridgeTable values('BIH', 'Bosnia and Herzegovina');
insert into BridgeTable values('RB', 'Botswana');
insert into BridgeTable values('BR', 'Brazil');
insert into BridgeTable values('BVIR', 'British Virgin Islands');
insert into BridgeTable values('BRU', 'Brunei');
insert into BridgeTable values('BG', 'Bulgaria');
insert into BridgeTable values('BF', 'Burkina Faso');
insert into BridgeTable values('BI', 'Burundi');
insert into BridgeTable values('K', 'Cambodia');
insert into BridgeTable values('CAM', 'Cameroon');
insert into BridgeTable values('CDN', 'Canada');
insert into BridgeTable values('CV', 'Cape Verde');
insert into BridgeTable values('CAYM', 'Cayman Islands');
insert into BridgeTable values('TCH', 'Chad');
insert into BridgeTable values('RCH', 'Chile');
insert into BridgeTable values('TJ', 'China');
insert into BridgeTable values('XMAS', 'Christmas Island');
insert into BridgeTable values('CO', 'Colombia');
insert into BridgeTable values('COM', 'Comoros');
insert into BridgeTable values('COOK', 'Cook Islands');
insert into BridgeTable values('CR', 'Costa Rica');
insert into BridgeTable values('HR', 'Croatia');
insert into BridgeTable values('C', 'Cuba');
insert into BridgeTable values('CY', 'Cyprus');
insert into BridgeTable values('DK', 'Denmark');
insert into BridgeTable values('DJI', 'Djibouti');
insert into BridgeTable values('WD', 'Dominica');
insert into BridgeTable values('EC', 'Ecuador');
insert into BridgeTable values('ET', 'Egypt');
insert into BridgeTable values('ES', 'El Salvador');
insert into BridgeTable values('GQ', 'Equatorial Guinea');
insert into BridgeTable values('ER', 'Eritrea');
insert into BridgeTable values('EW', 'Estonia');
insert into BridgeTable values('ETH', 'Ethiopia');
insert into BridgeTable values('FJI', 'Fiji');
insert into BridgeTable values('SF', 'Finland');
insert into BridgeTable values('F', 'France');
insert into BridgeTable values('FGU', 'French Guiana');
insert into BridgeTable values('FPOL', 'French Polynesia');
insert into BridgeTable values('G', 'Gabon');
insert into BridgeTable values('WAG', 'Gambia');
insert into BridgeTable values('GE', 'Georgia');
insert into BridgeTable values('D', 'Germany');
insert into BridgeTable values('GH', 'Ghana');
insert into BridgeTable values('GBZ', 'Gibraltar');
insert into BridgeTable values('GR', 'Greece');
insert into BridgeTable values('GROX', 'Greenland');
insert into BridgeTable values('WG', 'Grenada');
insert into BridgeTable values('GUAD', 'Guadeloupe');
insert into BridgeTable values('GUAM', 'Guam');
insert into BridgeTable values('GCA', 'Guatemala');
insert into BridgeTable values('GBG', 'Guernsey');
insert into BridgeTable values('RG', 'Guinea');
insert into BridgeTable values('GNB', 'Guinea-Bissau');
insert into BridgeTable values('GUY', 'Guyana');
insert into BridgeTable values('RH', 'Haiti');
insert into BridgeTable values('V', 'Holy See');
insert into BridgeTable values('HCA', 'Honduras');
insert into BridgeTable values('H', 'Hungary');
insert into BridgeTable values('IS', 'Iceland');
insert into BridgeTable values('IND', 'India');
insert into BridgeTable values('RI', 'Indonesia');
insert into BridgeTable values('IR', 'Iran');
insert into BridgeTable values('IRQ', 'Iraq');
insert into BridgeTable values('IRL', 'Ireland');
insert into BridgeTable values('IL', 'Israel');
insert into BridgeTable values('I', 'Italy');
insert into BridgeTable values('JA', 'Jamaica');
insert into BridgeTable values('J', 'Japan');
insert into BridgeTable values('GBJ', 'Jersey');
insert into BridgeTable values('JOR', 'Jordan');
insert into BridgeTable values('EAK', 'Kenya');
insert into BridgeTable values('KIR', 'Kiribati');
insert into BridgeTable values('KOS', 'Kosovo');
insert into BridgeTable values('KWT', 'Kuwait');
insert into BridgeTable values('KGZ', 'Kyrgyzstan');
insert into BridgeTable values('LAO', 'Laos');
insert into BridgeTable values('LV', 'Latvia');
insert into BridgeTable values('RL', 'Lebanon');
insert into BridgeTable values('LS', 'Lesotho');
insert into BridgeTable values('LB', 'Liberia');
insert into BridgeTable values('LAR', 'Libya');
insert into BridgeTable values('FL', 'Liechtenstein');
insert into BridgeTable values('LT', 'Lithuania');
insert into BridgeTable values('L', 'Luxembourg');
insert into BridgeTable values('RM', 'Madagascar');
insert into BridgeTable values('MW', 'Malawi');
insert into BridgeTable values('MAL', 'Malaysia');
insert into BridgeTable values('MV', 'Maldives');
insert into BridgeTable values('RMM', 'Mali');
insert into BridgeTable values('M', 'Malta');
insert into BridgeTable values('MH', 'Marshall Islands');
insert into BridgeTable values('MART', 'Martinique');
insert into BridgeTable values('RIM', 'Mauritania');
insert into BridgeTable values('MS', 'Mauritius');
insert into BridgeTable values('MAYO', 'Mayotte');
insert into BridgeTable values('MEX', 'Mexico');
insert into BridgeTable values('MD', 'Moldova');
insert into BridgeTable values('MC', 'Monaco');
insert into BridgeTable values('MNG', 'Mongolia');
insert into BridgeTable values('MNE', 'Montenegro');
insert into BridgeTable values('MNTS', 'Montserrat');
insert into BridgeTable values('MA', 'Morocco');
insert into BridgeTable values('MOC', 'Mozambique');
insert into BridgeTable values('MYA', 'Myanmar');
insert into BridgeTable values('NAM', 'Namibia');
insert into BridgeTable values('NAU', 'Nauru');
insert into BridgeTable values('NEP', 'Nepal');
insert into BridgeTable values('NL', 'Netherlands');
insert into BridgeTable values('NA', 'Netherlands Antilles');
insert into BridgeTable values('NCA', 'New Caledonia');
insert into BridgeTable values('NZ', 'New Zealand');
insert into BridgeTable values('NIC', 'Nicaragua');
insert into BridgeTable values('RN', 'Niger');
insert into BridgeTable values('WAN', 'Nigeria');
insert into BridgeTable values('NIUE', 'Niue');
insert into BridgeTable values('NORF', 'Norfolk Island');
insert into BridgeTable values('NMIS', 'Northern Mariana Islands');
insert into BridgeTable values('N', 'Norway');
insert into BridgeTable values('OM', 'Oman');
insert into BridgeTable values('PK', 'Pakistan');
insert into BridgeTable values('PAL', 'Palau');
insert into BridgeTable values('PA', 'Panama');
insert into BridgeTable values('PNG', 'Papua New Guinea');
insert into BridgeTable values('PY', 'Paraguay');
insert into BridgeTable values('PE', 'Peru');
insert into BridgeTable values('RP', 'Philippines');
insert into BridgeTable values('PL', 'Poland');
insert into BridgeTable values('P', 'Portugal');
insert into BridgeTable values('PR', 'Puerto Rico');
insert into BridgeTable values('Q', 'Qatar');
insert into BridgeTable values('REUN', 'Reunion');
insert into BridgeTable values('RO', 'Romania');
insert into BridgeTable values('R', 'Russia');
insert into BridgeTable values('RWA', 'Rwanda');
insert into BridgeTable values('HELX', 'Saint Helena');
insert into BridgeTable values('KN', 'Saint Kitts and Nevis');
insert into BridgeTable values('WL', 'Saint Lucia');
insert into BridgeTable values('SMAR', 'Saint Martin');
insert into BridgeTable values('WV', 'Saint Vincent and the Grenadines');
insert into BridgeTable values('WS', 'Samoa');
insert into BridgeTable values('RSM', 'San Marino');
insert into BridgeTable values('STP', 'Sao Tome and Principe');
insert into BridgeTable values('SA', 'Saudi Arabia');
insert into BridgeTable values('SN', 'Senegal');
insert into BridgeTable values('SRB', 'Serbia');
insert into BridgeTable values('SY', 'Seychelles');
insert into BridgeTable values('WAL', 'Sierra Leone');
insert into BridgeTable values('SGP', 'Singapore');
insert into BridgeTable values('SLO', 'Slovenia');
insert into BridgeTable values('SLB', 'Solomon Islands');
insert into BridgeTable values('SP', 'Somalia');
insert into BridgeTable values('RSA', 'South Africa');
insert into BridgeTable values('E', 'Spain');
insert into BridgeTable values('CL', 'Sri Lanka');
insert into BridgeTable values('SUD', 'Sudan');
insert into BridgeTable values('SME', 'Suriname');
insert into BridgeTable values('SVAX', 'Svalbard');
insert into BridgeTable values('SD', 'Swaziland');
insert into BridgeTable values('S', 'Sweden');
insert into BridgeTable values('CH', 'Switzerland');
insert into BridgeTable values('SYR', 'Syria');
insert into BridgeTable values('RC', 'Taiwan');
insert into BridgeTable values('TAD', 'Tajikistan');
insert into BridgeTable values('EAT', 'Tanzania');
insert into BridgeTable values('THA', 'Thailand');
insert into BridgeTable values('TL', 'Timor-Leste');
insert into BridgeTable values('RT', 'Togo');
insert into BridgeTable values('TO', 'Tonga');
insert into BridgeTable values('TT', 'Trinidad and Tobago');
insert into BridgeTable values('TN', 'Tunisia');
insert into BridgeTable values('TR', 'Turkey');
insert into BridgeTable values('TM', 'Turkmenistan');
insert into BridgeTable values('TUCA', 'Turks and Caicos Islands');
insert into BridgeTable values('TUV', 'Tuvalu');
insert into BridgeTable values('EAU', 'Uganda');
insert into BridgeTable values('UA', 'Ukraine');
insert into BridgeTable values('UAE', 'United Arab Emirates');
insert into BridgeTable values('GB', 'United Kingdom');
insert into BridgeTable values('USA', 'United States');
insert into BridgeTable values('ROU', 'Uruguay');
insert into BridgeTable values('UZB', 'Uzbekistan');
insert into BridgeTable values('VU', 'Vanuatu');
insert into BridgeTable values('YV', 'Venezuela');
insert into BridgeTable values('VN', 'Vietnam');
insert into BridgeTable values('WSA', 'Western Sahara');
insert into BridgeTable values('Z', 'Zambia');
insert into BridgeTable values('ZW', 'Zimbabwe');
